---

- hosts: node2
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  become: yes
  roles:
    - role: k3s/master_token

- hosts: node2
  become: yes
  roles:
    - role: k3s/node
