
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: nclink
type: Opaque
stringData:
  mongo-root-username: someone
  mongo-root-password: t0p-Secret

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: nclink
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  namespace: nclink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: db-data
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nclink-role
                operator: In
                values:
                - broker
      tolerations:
      - effect: NoExecute
        key: nclink
        operator: Equal
        value: "true"
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: mongo-data

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: nclink
spec:
  clusterIP: None
  selector:
    app: mongodb

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: nclink
type: Opaque
stringData:
  mongo-express-username: someadmin
  mongo-express-password: t0p-Secret-yet

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: nclink
data:
  databaseURL: mongodb-headless

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: nclink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:0.54.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-express-secret
              key: mongo-express-username
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-express-secret
              key: mongo-express-password
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: databaseURL

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: nclink
spec:
  selector:
    app: mongo-express
  ports:
  - port: 8081
    targetPort: 8081

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-ingress
  namespace: nclink
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: mongo.lightcat.pub
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongo-express-service
            port:
              number: 8081
